### PR TITLE
fix(search/file-upload): added validation for maximum allowed keyword…

### LINKED ISSUE #9: [Feature] Implement validation logic to process less than 100 keywords
## Issue

The current implementation does not prevent the processing of more than 100 keywords:

https://github.com/tajul-saajan/google-searcher/blob/36a95d4f0ee6216e9fb4abdb15038b12d2f25d54/src/search/search.controller.ts#L31-L44

## Expected

To improve the UX, the content of the CSV should be processed and validated before starting any scraping. The UI must display an error if a user uploads more than 100 keywords.

> [!NOTE]
> It is part of the requirements:
>  requirements

### PR DESCRIPTION
**Pull request by tajul-saajan**
resolves #9 

After CSV file parsing, it checks for parsed data length
if the length exceeds the limit, it does not perform a search and sets a session message for validation violation

### CODE REVIEW

File: src/search/search.controller.ts [hunk 1]
```diff
@@ -38,19 +39,24 @@ export class SearchController {
     @Res() response: Response,
     @Req() request: Request,
   ) {
-    console.log(file);
+    const sessionData = {
```
Comment (olivierobert) [inline src/search/search.controller.ts:42]: Flash messages can be implemented via https://github.com/jaredhanson/connect-flash (Express-based solution)

File: src/search/search.controller.ts [hunk 2]
```diff
@@ -38,19 +39,24 @@ export class SearchController {
...
+      success: true,
+      message:
+        'Your file has been uploaded. Your results will be displayed as they are available',
+    };
     const keywords = await this.parser.parseData<CsvField>(file);
     this.service.deleteFile();
-    this.eventEmitter.emit('file.uploaded', new FileUploadedEvent(keywords));
+    if (keywords.length > this.MAX_ALLOWED_KEYWORDS) {
```
Comment (olivierobert) [inline src/search/search.controller.ts:49]: It might be best to place this logic in the parser to keep the controller lean.
